version: '3'
services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:5432'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db